version: '3.9'
services:
  app:
    container_name: gap-service-app
    build: .
    ports:
      - "3001:3001"
    restart: on-failure
    networks:
      - gap-project

networks:
  gap-project:
    driver: bridge