version: '3.9'
services:
  postgres:
    container_name: postgres_gap
    image: postgres:14.13
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "@4dariEmpat"
    networks:
      - gap-project

  redis:
    container_name: redis_gap
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - gap-project
  
  tracing:
    container_name: jaegertracing
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

networks:
  gap-project:
    driver: bridge